### PR TITLE
Bump 'Tested up to' to `6.0`

### PR DESCRIPTION
**Pull request by kienstra**
* Bump 'Tested up to' version to 6.0
* To deploy to SVN, approve the CircleCI job

### CODE REVIEW

**Comment by kienstra** [comment]
This deployed [as expected](https://plugins.trac.wordpress.org/changeset?old=2282409&old_path=seo-data-transporter&new=2725600&new_path=seo-data-transporter)

**Review by johnstonphilip — APPROVED** [review]

**Comment by kienstra** [comment]
Thanks, @johnstonphilip! That was fast 🚀

**Comment by kienstra** [comment]
Hi @dreamwhisper,
Could you review this when you have a chance?

A sanity check would do it. Thanks!

**Review by dreamwhisper — APPROVED** [review]

**Comment by kienstra** [comment]
Thanks, @dreamwhisper!

**Pull request merged**
